### ISSUE TITLE
error while loading

### ISSUE THREAD

**Issue by boxochi** [BetterWayElectronics/ps4-nor-validator#2]
hi 
error when loading in win11
![Screenshot 2023-02-11 004725](https://user-images.githubusercontent.com/14182674/218199879-997dfc77-8cbd-493d-8d4d-8ed50f5dd8d9.png)

**Comment by BetterWayElectronics** [comment]
It because you have not generated a HWID with the software (and or you are a trial user). **This will be fixed in the next version.**
